language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t stephengrider/docker-test -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/docker-test npm run test -- --coverage