language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t stephengrider/docker-test -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/docker-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-177715349144"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"